const userTypes = {
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_USER_START: "SIGN_OUT_USER_START",
  SIGN_OUT_USER_SUCCESS: "SIGN_OUT_USER_SUCCESS",
  SIGN_UP_USER_START: "SIGN_UP_USER_START",
  RESET_PASSWORD_START: "RESET_PASSWORD_START",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_AUTH_FORMS: "RESET_AUTH_FORMS",
  USER_ERROR: "USER_ERROR",
  /// OLD TYPES TO DELETE
  //   SET_CURRENT_USER: "SET_CURRENT_USER",
  //   SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  //   RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  //   RESET_PASSWORD_ERROR: "RESET_PASSWORD_ERROR",
  //
  ////////
};

export default userTypes;
